blocked_commands:
  # --------- Minecraft ---------
  - 'minecraft:tell'
  - 'me'
  - 'minecraft:me'
  - 'op'
  - 'minecraft:op'
  - 'deop'
  - 'minecraft:deop'
  - 'stop'
  - 'minecraft:stop'
  - 'say'
  - 'minecraft:say'
  # --------- Bukkit ---------
  - 'icanhasbukkit'
  - 'pl'
  - 'bukkit:pl'
  - 'plugins'
  - 'bukkit:plugins'
  - 'ver'
  - 'bukkit:ver'
  - 'version'
  - 'bukkit:version'
  - '?'
  - 'bukkit:?'
  - 'about'
  - 'bukkit:about'
  - 'help'
  - 'bukkit:help'
  - 'reload'
  - 'bukkit:reload'
  - 'rl'
  - 'bukkit:rl'
  # --------- Spigot ---------
  - 'restart'
  - 'spigot:restart'